//stream.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.5.1
// source: mq.proto

package mqV1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Mq_PushData_FullMethodName = "/Mq/PushData"
	Mq_PullData_FullMethodName = "/Mq/PullData"
)

// MqClient is the client API for Mq service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MqClient interface {
	PushData(ctx context.Context, in *PushDataReq, opts ...grpc.CallOption) (*PushDataRes, error)
	PullData(ctx context.Context, in *PullDataReq, opts ...grpc.CallOption) (Mq_PullDataClient, error)
}

type mqClient struct {
	cc grpc.ClientConnInterface
}

func NewMqClient(cc grpc.ClientConnInterface) MqClient {
	return &mqClient{cc}
}

func (c *mqClient) PushData(ctx context.Context, in *PushDataReq, opts ...grpc.CallOption) (*PushDataRes, error) {
	out := new(PushDataRes)
	err := c.cc.Invoke(ctx, Mq_PushData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mqClient) PullData(ctx context.Context, in *PullDataReq, opts ...grpc.CallOption) (Mq_PullDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &Mq_ServiceDesc.Streams[0], Mq_PullData_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &mqPullDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Mq_PullDataClient interface {
	Recv() (*PullDataRes, error)
	grpc.ClientStream
}

type mqPullDataClient struct {
	grpc.ClientStream
}

func (x *mqPullDataClient) Recv() (*PullDataRes, error) {
	m := new(PullDataRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MqServer is the server API for Mq service.
// All implementations must embed UnimplementedMqServer
// for forward compatibility
type MqServer interface {
	PushData(context.Context, *PushDataReq) (*PushDataRes, error)
	PullData(*PullDataReq, Mq_PullDataServer) error
	mustEmbedUnimplementedMqServer()
}

// UnimplementedMqServer must be embedded to have forward compatible implementations.
type UnimplementedMqServer struct {
}

func (UnimplementedMqServer) PushData(context.Context, *PushDataReq) (*PushDataRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushData not implemented")
}
func (UnimplementedMqServer) PullData(*PullDataReq, Mq_PullDataServer) error {
	return status.Errorf(codes.Unimplemented, "method PullData not implemented")
}
func (UnimplementedMqServer) mustEmbedUnimplementedMqServer() {}

// UnsafeMqServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MqServer will
// result in compilation errors.
type UnsafeMqServer interface {
	mustEmbedUnimplementedMqServer()
}

func RegisterMqServer(s grpc.ServiceRegistrar, srv MqServer) {
	s.RegisterService(&Mq_ServiceDesc, srv)
}

func _Mq_PushData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqServer).PushData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mq_PushData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqServer).PushData(ctx, req.(*PushDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mq_PullData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullDataReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MqServer).PullData(m, &mqPullDataServer{stream})
}

type Mq_PullDataServer interface {
	Send(*PullDataRes) error
	grpc.ServerStream
}

type mqPullDataServer struct {
	grpc.ServerStream
}

func (x *mqPullDataServer) Send(m *PullDataRes) error {
	return x.ServerStream.SendMsg(m)
}

// Mq_ServiceDesc is the grpc.ServiceDesc for Mq service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mq_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Mq",
	HandlerType: (*MqServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushData",
			Handler:    _Mq_PushData_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PullData",
			Handler:       _Mq_PullData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mq.proto",
}
