//stream.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.5.1
// source: mq.proto

package protoMq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 推送数据参数
type ReqPushData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WaitRes bool   `protobuf:"varint,1,opt,name=WaitRes,proto3" json:"WaitRes,omitempty"` // 等待服务器响应
	Ch      string `protobuf:"bytes,2,opt,name=Ch,proto3" json:"Ch,omitempty"`            // 频道
	Data    []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`        // 数据内容
}

func (x *ReqPushData) Reset() {
	*x = ReqPushData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPushData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPushData) ProtoMessage() {}

func (x *ReqPushData) ProtoReflect() protoreflect.Message {
	mi := &file_mq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPushData.ProtoReflect.Descriptor instead.
func (*ReqPushData) Descriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{0}
}

func (x *ReqPushData) GetWaitRes() bool {
	if x != nil {
		return x.WaitRes
	}
	return false
}

func (x *ReqPushData) GetCh() string {
	if x != nil {
		return x.Ch
	}
	return ""
}

func (x *ReqPushData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 推送数据返回
type ResPushData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrNum int32 `protobuf:"varint,1,opt,name=ErrNum,proto3" json:"ErrNum,omitempty"` // 错误编号，0为正常
}

func (x *ResPushData) Reset() {
	*x = ResPushData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResPushData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResPushData) ProtoMessage() {}

func (x *ResPushData) ProtoReflect() protoreflect.Message {
	mi := &file_mq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResPushData.ProtoReflect.Descriptor instead.
func (*ResPushData) Descriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{1}
}

func (x *ResPushData) GetErrNum() int32 {
	if x != nil {
		return x.ErrNum
	}
	return 0
}

// 拉取数据参数
type ReqPullData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User   string `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`      // 用户
	Ch     string `protobuf:"bytes,2,opt,name=Ch,proto3" json:"Ch,omitempty"`          // 频道
	BKType bool   `protobuf:"varint,3,opt,name=BKType,proto3" json:"BKType,omitempty"` // bucket参数类型 0:使用远端存储的位置 1:使用传递的参数
	BKName string `protobuf:"bytes,4,opt,name=BKName,proto3" json:"BKName,omitempty"`  // bucket name
	BKKey  string `protobuf:"bytes,5,opt,name=BKKey,proto3" json:"BKKey,omitempty"`    // bucket key
}

func (x *ReqPullData) Reset() {
	*x = ReqPullData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mq_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPullData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPullData) ProtoMessage() {}

func (x *ReqPullData) ProtoReflect() protoreflect.Message {
	mi := &file_mq_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPullData.ProtoReflect.Descriptor instead.
func (*ReqPullData) Descriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{2}
}

func (x *ReqPullData) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ReqPullData) GetCh() string {
	if x != nil {
		return x.Ch
	}
	return ""
}

func (x *ReqPullData) GetBKType() bool {
	if x != nil {
		return x.BKType
	}
	return false
}

func (x *ReqPullData) GetBKName() string {
	if x != nil {
		return x.BKName
	}
	return ""
}

func (x *ReqPullData) GetBKKey() string {
	if x != nil {
		return x.BKKey
	}
	return ""
}

// 拉取数据返回
type ResPullData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrNum int32  `protobuf:"varint,1,opt,name=ErrNum,proto3" json:"ErrNum,omitempty"` // 错误编号，0为正常
	BKName string `protobuf:"bytes,2,opt,name=BKName,proto3" json:"BKName,omitempty"`  // bucket name
	BKKey  string `protobuf:"bytes,3,opt,name=BKKey,proto3" json:"BKKey,omitempty"`    // bucket key
	Data   []byte `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`      // 数据内容
}

func (x *ResPullData) Reset() {
	*x = ResPullData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mq_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResPullData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResPullData) ProtoMessage() {}

func (x *ResPullData) ProtoReflect() protoreflect.Message {
	mi := &file_mq_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResPullData.ProtoReflect.Descriptor instead.
func (*ResPullData) Descriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{3}
}

func (x *ResPullData) GetErrNum() int32 {
	if x != nil {
		return x.ErrNum
	}
	return 0
}

func (x *ResPullData) GetBKName() string {
	if x != nil {
		return x.BKName
	}
	return ""
}

func (x *ResPullData) GetBKKey() string {
	if x != nil {
		return x.BKKey
	}
	return ""
}

func (x *ResPullData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_mq_proto protoreflect.FileDescriptor

var file_mq_proto_rawDesc = []byte{
	0x0a, 0x08, 0x6d, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x0b, 0x52, 0x65,
	0x71, 0x50, 0x75, 0x73, 0x68, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x57, 0x61, 0x69,
	0x74, 0x52, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x57, 0x61, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x43, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x43, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x25, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x50, 0x75,
	0x73, 0x68, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x72, 0x72, 0x4e, 0x75, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x45, 0x72, 0x72, 0x4e, 0x75, 0x6d, 0x22, 0x77,
	0x0a, 0x0b, 0x52, 0x65, 0x71, 0x50, 0x75, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a,
	0x04, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x43, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x43,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x4b, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x42, 0x4b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x4b, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x4b, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x42, 0x4b, 0x4b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x42, 0x4b, 0x4b, 0x65, 0x79, 0x22, 0x67, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x50, 0x75,
	0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x72, 0x72, 0x4e, 0x75, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x45, 0x72, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x16,
	0x0a, 0x06, 0x42, 0x4b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x42, 0x4b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x42, 0x4b, 0x4b, 0x65, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x42, 0x4b, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x32, 0x5a, 0x0a, 0x02, 0x4d, 0x71, 0x12, 0x2a, 0x0a, 0x08, 0x50, 0x75, 0x73, 0x68, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x0c, 0x2e, 0x52, 0x65, 0x71, 0x50, 0x75, 0x73, 0x68, 0x44, 0x61, 0x74, 0x61,
	0x1a, 0x0c, 0x2e, 0x52, 0x65, 0x73, 0x50, 0x75, 0x73, 0x68, 0x44, 0x61, 0x74, 0x61, 0x28, 0x01,
	0x30, 0x01, 0x12, 0x28, 0x0a, 0x08, 0x50, 0x75, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0c,
	0x2e, 0x52, 0x65, 0x71, 0x50, 0x75, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x0c, 0x2e, 0x52,
	0x65, 0x73, 0x50, 0x75, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x30, 0x01, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x4d, 0x71, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_mq_proto_rawDescOnce sync.Once
	file_mq_proto_rawDescData = file_mq_proto_rawDesc
)

func file_mq_proto_rawDescGZIP() []byte {
	file_mq_proto_rawDescOnce.Do(func() {
		file_mq_proto_rawDescData = protoimpl.X.CompressGZIP(file_mq_proto_rawDescData)
	})
	return file_mq_proto_rawDescData
}

var file_mq_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mq_proto_goTypes = []interface{}{
	(*ReqPushData)(nil), // 0: ReqPushData
	(*ResPushData)(nil), // 1: ResPushData
	(*ReqPullData)(nil), // 2: ReqPullData
	(*ResPullData)(nil), // 3: ResPullData
}
var file_mq_proto_depIdxs = []int32{
	0, // 0: Mq.PushData:input_type -> ReqPushData
	2, // 1: Mq.PullData:input_type -> ReqPullData
	1, // 2: Mq.PushData:output_type -> ResPushData
	3, // 3: Mq.PullData:output_type -> ResPullData
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mq_proto_init() }
func file_mq_proto_init() {
	if File_mq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPushData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mq_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResPushData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mq_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPullData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mq_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResPullData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mq_proto_goTypes,
		DependencyIndexes: file_mq_proto_depIdxs,
		MessageInfos:      file_mq_proto_msgTypes,
	}.Build()
	File_mq_proto = out.File
	file_mq_proto_rawDesc = nil
	file_mq_proto_goTypes = nil
	file_mq_proto_depIdxs = nil
}
