//stream.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.5.1
// source: mq.proto

package protoMq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType int32

const (
	DataType_DataOnly DataType = 0 // 仅数据
	DataType_DataEnd  DataType = 1 // 数据和结束符
	DataType_EndOnly  DataType = 2 // 仅结束符
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "DataOnly",
		1: "DataEnd",
		2: "EndOnly",
	}
	DataType_value = map[string]int32{
		"DataOnly": 0,
		"DataEnd":  1,
		"EndOnly":  2,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_mq_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_mq_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{0}
}

type BKType int32

const (
	BKType_RemoteSaved      BKType = 0 // 使用远端位置，没有则报错
	BKType_RemoteDefaultNow BKType = 1 // 使用远端位置,没有则使用当前位置
	BKType_RemoteDefaultAll BKType = 2 // 使用远端位置,没有读取出所有的
	BKType_UserSet          BKType = 3 // 使用指定位置
)

// Enum value maps for BKType.
var (
	BKType_name = map[int32]string{
		0: "RemoteSaved",
		1: "RemoteDefaultNow",
		2: "RemoteDefaultAll",
		3: "UserSet",
	}
	BKType_value = map[string]int32{
		"RemoteSaved":      0,
		"RemoteDefaultNow": 1,
		"RemoteDefaultAll": 2,
		"UserSet":          3,
	}
)

func (x BKType) Enum() *BKType {
	p := new(BKType)
	*p = x
	return p
}

func (x BKType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BKType) Descriptor() protoreflect.EnumDescriptor {
	return file_mq_proto_enumTypes[1].Descriptor()
}

func (BKType) Type() protoreflect.EnumType {
	return &file_mq_proto_enumTypes[1]
}

func (x BKType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BKType.Descriptor instead.
func (BKType) EnumDescriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{1}
}

// 推送数据参数
type ReqPushData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataType DataType `protobuf:"varint,1,opt,name=DataType,proto3,enum=DataType" json:"DataType,omitempty"` // 数据说明
	Ch       string   `protobuf:"bytes,2,opt,name=Ch,proto3" json:"Ch,omitempty"`                            // 频道
	Data     []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`                        // 数据内容
}

func (x *ReqPushData) Reset() {
	*x = ReqPushData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPushData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPushData) ProtoMessage() {}

func (x *ReqPushData) ProtoReflect() protoreflect.Message {
	mi := &file_mq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPushData.ProtoReflect.Descriptor instead.
func (*ReqPushData) Descriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{0}
}

func (x *ReqPushData) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_DataOnly
}

func (x *ReqPushData) GetCh() string {
	if x != nil {
		return x.Ch
	}
	return ""
}

func (x *ReqPushData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 推送数据返回
type ResPushData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrNum int32 `protobuf:"varint,1,opt,name=ErrNum,proto3" json:"ErrNum,omitempty"` // 错误编号，0为正常
}

func (x *ResPushData) Reset() {
	*x = ResPushData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResPushData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResPushData) ProtoMessage() {}

func (x *ResPushData) ProtoReflect() protoreflect.Message {
	mi := &file_mq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResPushData.ProtoReflect.Descriptor instead.
func (*ResPushData) Descriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{1}
}

func (x *ResPushData) GetErrNum() int32 {
	if x != nil {
		return x.ErrNum
	}
	return 0
}

// 拉取数据参数
type ReqPullData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User   string `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`                  // 用户
	Ch     string `protobuf:"bytes,2,opt,name=Ch,proto3" json:"Ch,omitempty"`                      // 频道
	BKType BKType `protobuf:"varint,3,opt,name=BKType,proto3,enum=BKType" json:"BKType,omitempty"` // bucket参数类型
	BKName string `protobuf:"bytes,4,opt,name=BKName,proto3" json:"BKName,omitempty"`              // bucket name
	BKKey  string `protobuf:"bytes,5,opt,name=BKKey,proto3" json:"BKKey,omitempty"`                // bucket key
}

func (x *ReqPullData) Reset() {
	*x = ReqPullData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mq_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPullData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPullData) ProtoMessage() {}

func (x *ReqPullData) ProtoReflect() protoreflect.Message {
	mi := &file_mq_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPullData.ProtoReflect.Descriptor instead.
func (*ReqPullData) Descriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{2}
}

func (x *ReqPullData) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ReqPullData) GetCh() string {
	if x != nil {
		return x.Ch
	}
	return ""
}

func (x *ReqPullData) GetBKType() BKType {
	if x != nil {
		return x.BKType
	}
	return BKType_RemoteSaved
}

func (x *ReqPullData) GetBKName() string {
	if x != nil {
		return x.BKName
	}
	return ""
}

func (x *ReqPullData) GetBKKey() string {
	if x != nil {
		return x.BKKey
	}
	return ""
}

// 拉取数据返回
type ResPullData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrNum int32  `protobuf:"varint,1,opt,name=ErrNum,proto3" json:"ErrNum,omitempty"` // 错误编号，0为正常
	BKName string `protobuf:"bytes,2,opt,name=BKName,proto3" json:"BKName,omitempty"`  // bucket name
	BKKey  string `protobuf:"bytes,3,opt,name=BKKey,proto3" json:"BKKey,omitempty"`    // bucket key
	Data   []byte `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`      // 数据内容
}

func (x *ResPullData) Reset() {
	*x = ResPullData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mq_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResPullData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResPullData) ProtoMessage() {}

func (x *ResPullData) ProtoReflect() protoreflect.Message {
	mi := &file_mq_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResPullData.ProtoReflect.Descriptor instead.
func (*ResPullData) Descriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{3}
}

func (x *ResPullData) GetErrNum() int32 {
	if x != nil {
		return x.ErrNum
	}
	return 0
}

func (x *ResPullData) GetBKName() string {
	if x != nil {
		return x.BKName
	}
	return ""
}

func (x *ResPullData) GetBKKey() string {
	if x != nil {
		return x.BKKey
	}
	return ""
}

func (x *ResPullData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_mq_proto protoreflect.FileDescriptor

var file_mq_proto_rawDesc = []byte{
	0x0a, 0x08, 0x6d, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x0b, 0x52, 0x65,
	0x71, 0x50, 0x75, 0x73, 0x68, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x08, 0x44, 0x61, 0x74,
	0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x43, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x43, 0x68,
	0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x25, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x50, 0x75, 0x73, 0x68, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x72, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x45, 0x72, 0x72, 0x4e, 0x75, 0x6d, 0x22, 0x80, 0x01, 0x0a, 0x0b,
	0x52, 0x65, 0x71, 0x50, 0x75, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x55,
	0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x0e, 0x0a, 0x02, 0x43, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x43, 0x68, 0x12,
	0x1f, 0x0a, 0x06, 0x42, 0x4b, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x07, 0x2e, 0x42, 0x4b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x42, 0x4b, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x42, 0x4b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x42, 0x4b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x42, 0x4b, 0x4b, 0x65,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x42, 0x4b, 0x4b, 0x65, 0x79, 0x22, 0x67,
	0x0a, 0x0b, 0x52, 0x65, 0x73, 0x50, 0x75, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a,
	0x06, 0x45, 0x72, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x45,
	0x72, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x4b, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x4b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x42, 0x4b, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x42, 0x4b,
	0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x2a, 0x32, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x4f, 0x6e, 0x6c, 0x79, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x64, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x45, 0x6e, 0x64, 0x4f, 0x6e, 0x6c, 0x79, 0x10, 0x02, 0x2a, 0x52, 0x0a, 0x06, 0x42,
	0x4b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53,
	0x61, 0x76, 0x65, 0x64, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4e, 0x6f, 0x77, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10,
	0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x41, 0x6c, 0x6c,
	0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x74, 0x10, 0x03, 0x32,
	0x5a, 0x0a, 0x02, 0x4d, 0x71, 0x12, 0x2a, 0x0a, 0x08, 0x50, 0x75, 0x73, 0x68, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x0c, 0x2e, 0x52, 0x65, 0x71, 0x50, 0x75, 0x73, 0x68, 0x44, 0x61, 0x74, 0x61, 0x1a,
	0x0c, 0x2e, 0x52, 0x65, 0x73, 0x50, 0x75, 0x73, 0x68, 0x44, 0x61, 0x74, 0x61, 0x28, 0x01, 0x30,
	0x01, 0x12, 0x28, 0x0a, 0x08, 0x50, 0x75, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0c, 0x2e,
	0x52, 0x65, 0x71, 0x50, 0x75, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x0c, 0x2e, 0x52, 0x65,
	0x73, 0x50, 0x75, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x30, 0x01, 0x42, 0x0c, 0x5a, 0x0a, 0x2e,
	0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x4d, 0x71, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_mq_proto_rawDescOnce sync.Once
	file_mq_proto_rawDescData = file_mq_proto_rawDesc
)

func file_mq_proto_rawDescGZIP() []byte {
	file_mq_proto_rawDescOnce.Do(func() {
		file_mq_proto_rawDescData = protoimpl.X.CompressGZIP(file_mq_proto_rawDescData)
	})
	return file_mq_proto_rawDescData
}

var file_mq_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_mq_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mq_proto_goTypes = []interface{}{
	(DataType)(0),       // 0: DataType
	(BKType)(0),         // 1: BKType
	(*ReqPushData)(nil), // 2: ReqPushData
	(*ResPushData)(nil), // 3: ResPushData
	(*ReqPullData)(nil), // 4: ReqPullData
	(*ResPullData)(nil), // 5: ResPullData
}
var file_mq_proto_depIdxs = []int32{
	0, // 0: ReqPushData.DataType:type_name -> DataType
	1, // 1: ReqPullData.BKType:type_name -> BKType
	2, // 2: Mq.PushData:input_type -> ReqPushData
	4, // 3: Mq.PullData:input_type -> ReqPullData
	3, // 4: Mq.PushData:output_type -> ResPushData
	5, // 5: Mq.PullData:output_type -> ResPullData
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mq_proto_init() }
func file_mq_proto_init() {
	if File_mq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPushData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mq_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResPushData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mq_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPullData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mq_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResPullData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mq_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mq_proto_goTypes,
		DependencyIndexes: file_mq_proto_depIdxs,
		EnumInfos:         file_mq_proto_enumTypes,
		MessageInfos:      file_mq_proto_msgTypes,
	}.Build()
	File_mq_proto = out.File
	file_mq_proto_rawDesc = nil
	file_mq_proto_goTypes = nil
	file_mq_proto_depIdxs = nil
}
